apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: sample-vertx-kubernetes
build:
  artifacts:
    - image: account-vertx-service
      #      context: account-vertx-service
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
        buildpacks:
          - paketo-buildpacks/adoptium
          - paketo-buildpacks/java
        env:
          - BP_MAVEN_BUILD_ARGUMENTS=--pl account-vertx-service --am package -DskipTests
          - BP_MAVEN_BUILT_MODULE=account-vertx-service

#    - image: customer-vertx-service
#      #context: customer-vertx-service
#      buildpacks:
#        builder: paketobuildpacks/builder-jammy-base
#        buildpacks:
#          - paketo-buildpacks/adoptium
#          - paketo-buildpacks/java
#        env:
#          - BP_MAVEN_BUILD_ARGUMENTS=--pl customer-vertx-service --am package -DskipTests
#          - BP_MAVEN_BUILT_MODULE=customer-vertx-service
manifests:
  rawYaml:
    - "*/k8s/*.yaml"
    - "k8s/*.yaml"

deploy:
  kubectl: {}