apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-vertx-service
  namespace: vertx
spec:
  selector:
    matchLabels:
      app: customer-vertx-service
  template:
    metadata:
      labels:
        app: customer-vertx-service
    spec:
      containers:
      - name: customer-vertx-service
        image: customer-vertx-service
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb
                key: database-name
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-password
          - name: MONGO_URL
            value: mongodb
